# Site settings
title: Dorian Brennan
description: Architect, writer, thinker, and creator
url: "https://dorianbrennan.github.io"
baseurl: "/dorianbrennan"

# Author info
author:
  name: Dorian Brennan
  email: you@email.com
  location: Sydney
  bio: I'm a architect, writer, thinker, and creator based in Sydney. I write about technology, architecture, and space.
# Social links
social:
  twitter: dorian_brennan
  linkedin: dorian-brennan-54583525
  github: your_github

# Build settings
markdown: kramdown
permalink: /:categories/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Collections
collections:
  stories:
    output: true
    permalink: /stories/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
